/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chinsu.gui1;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Windows 10
 */
public class ChatJpanel extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form ChatJpanel
     */
    Socket sc = null;

    BufferedReader bf = null;
    DataOutputStream os = null;
    String name;
    public ChatJpanel(Socket s, String name) {
        try {
            initComponents();
            sc = s;
            bf = new BufferedReader(new InputStreamReader(sc.getInputStream()));
            os = new DataOutputStream(sc.getOutputStream());
            (new Thread(this)).start();
        } catch (IOException ex) {
            Logger.getLogger(ChatJpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.name = name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSend = new javax.swing.JButton();
        txtChatSend = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatHistory = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 153, 153));

        btnSend.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSend.setText("Gửi");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtChatSend.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtChatHistory.setColumns(20);
        txtChatHistory.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtChatHistory.setRows(5);
        jScrollPane1.setViewportView(txtChatHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtChatSend, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnSend)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChatSend, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem người dùng nhập tin nhắn hay chưa
        if (txtChatSend.getText().isEmpty()) {
            return;
        }
        try {
            os.writeBytes(name + ": " + txtChatSend.getText() +"\n");
            os.flush();
            txtChatHistory.append(name + ": " + txtChatSend.getText() + "\n");
            txtChatSend.setText("");
        } catch (IOException e) {
            System.out.println("Error while sendding messeger");
        }
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtChatHistory;
    private javax.swing.JTextField txtChatSend;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                if (sc != null) {
                    String msg = "";
                    while ((msg = bf.readLine()) != null) {                       
                        txtChatHistory.append(msg +"\n");
                    }
                }
            } catch (Exception e) {

            }
        }
    }
}
