/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chinsu.gui1;

import chinsu.object.distributor.Distributor;
import chinsu.object.distributor.DistributorImpl;
import chinsu.object.distributor.DistributorObject;
import chinsu.object.sql.Conditions;
import java.sql.ResultSet;
import java.util.concurrent.locks.Condition;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Windows 10
 */
public class DistributorPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorPanel
     */
    Distributor d = new DistributorImpl();
    Conditions cond = new Conditions();
    public DistributorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DistributorName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btreset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldanhsach = new javax.swing.JTable();
        txtphone = new javax.swing.JTextField();
        txtimamount = new javax.swing.JTextField();
        btadd = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        btreload = new javax.swing.JButton();
        btdel = new javax.swing.JButton();
        btaddfromexcel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rdname = new javax.swing.JRadioButton();
        rdaddress = new javax.swing.JRadioButton();
        rdphone = new javax.swing.JRadioButton();
        btfind = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        DistributorName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DistributorName.setText("Tên nhà cung cấp");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mã nhà cung cấp");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Địa chỉ");

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số điện thoại");

        btreset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng nhập");

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tbldanhsach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbldanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Địa chỉ", "Số điện thoại", "Số lượng nhập"
            }
        ));
        tbldanhsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldanhsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldanhsach);

        txtphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtimamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btadd.setText("Thêm ");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btedit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btedit.setText("Sửa");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        btreload.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btreload.setText("Tải lại");
        btreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreloadActionPerformed(evt);
            }
        });

        btdel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btdel.setText("Xóa");
        btdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelActionPerformed(evt);
            }
        });

        btaddfromexcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btaddfromexcel.setText("Thêm từ excel");
        btaddfromexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddfromexcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        btgroup.add(rdname);
        rdname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdname.setText("Tên");

        btgroup.add(rdaddress);
        rdaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdaddress.setText("Địa chỉ");

        btgroup.add(rdphone);
        rdphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdphone.setText("Số điện thoại");

        btfind.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btfind.setText("Tìm");
        btfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfindActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Quản lí nhà cung cấp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(2073, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1481, 1481, 1481))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DistributorName)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                            .addComponent(txtname))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtphone, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(txtimamount))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdphone)
                                    .addComponent(rdname)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdaddress)
                                        .addGap(39, 39, 39)
                                        .addComponent(btfind, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(361, 361, 361)
                                .addComponent(jLabel1)))
                        .addGap(158, 158, 158)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btaddfromexcel)
                        .addGap(18, 18, 18)
                        .addComponent(btadd)
                        .addGap(27, 27, 27)
                        .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btdel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btreload, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DistributorName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtimamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rdname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdaddress)
                                    .addComponent(btfind))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdphone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btadd)
                            .addComponent(btedit)
                            .addComponent(btdel)
                            .addComponent(btreload)
                            .addComponent(btreset)
                            .addComponent(btaddfromexcel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addGap(149, 149, 149)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelActionPerformed
        // TODO add your handling code here:
        if(txtid.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nhập id cần xóa");
        } else {
            DistributorObject dis = new DistributorObject();
            dis.setDistributor_id(Integer.parseInt(txtid.getText()));
            if(d.delDistributor(dis)) {
                JOptionPane.showMessageDialog(null, "Xóa thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi!!!");
            }
        }
        btreloadActionPerformed(evt);
    }//GEN-LAST:event_btdelActionPerformed

    private void btreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreloadActionPerformed
        // TODO add your handling code here:
        ResultSet rs = d.getDistributors("");
        tbldanhsach.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btreloadActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().trim().isEmpty() || txtaddress.getText().trim().isEmpty()||txtphone.getText().trim().isEmpty() || txtimamount.getText().trim().isEmpty()||txtid.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ dữ liệu");
        } else {
            DistributorObject dis = new DistributorObject();
            dis.setDistributor_id(Integer.parseInt(txtid.getText()));
            dis.setDistributor_name(txtname.getText());
            dis.setDistributor_address(txtaddress.getText());
            dis.setDistributor_phone(txtphone.getText());
            dis.setDistributor_imamount(Integer.parseInt(txtimamount.getText()));
            if(d.editDistributor(dis)) {
                JOptionPane.showMessageDialog(null, "Sửa thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Nhà phân phối này không tồn tại");
            }
        }
        btreloadActionPerformed(evt);
    }//GEN-LAST:event_bteditActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().trim().isEmpty() || txtaddress.getText().trim().isEmpty()||txtphone.getText().trim().isEmpty() || txtimamount.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin");
        } else {
            DistributorObject dis = new DistributorObject();
            dis.setDistributor_name(txtname.getText());
            dis.setDistributor_address(txtaddress.getText());
            dis.setDistributor_phone(txtphone.getText());
            dis.setDistributor_imamount(Integer.parseInt(txtimamount.getText()));
            if(d.addDistributor(dis)) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Nhà sản xuất này đã tồn tại");
            }
        }
        btreloadActionPerformed(evt);
    }//GEN-LAST:event_btaddActionPerformed

    private void tbldanhsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldanhsachMouseClicked
        // TODO add your handling code here:
        int index = tbldanhsach.getSelectedRow();
        TableModel model = tbldanhsach.getModel();
        txtid.setText(model.getValueAt(index, 0).toString());
        txtname.setText(model.getValueAt(index, 1).toString());
        txtaddress.setText(model.getValueAt(index, 2).toString());
        txtphone.setText(model.getValueAt(index, 3).toString());
        txtimamount.setText(model.getValueAt(index, 4).toString());
    }//GEN-LAST:event_tbldanhsachMouseClicked

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        txtaddress.setText("");
        txtid.setText("");
        txtname.setText("");
        txtphone.setText("");
        txtimamount.setText("");
    }//GEN-LAST:event_btresetActionPerformed

    private void btaddfromexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddfromexcelActionPerformed
        // TODO add your handling code here:
        ExcelAddDistributor j = new ExcelAddDistributor();
        j.setVisible(true);
    }//GEN-LAST:event_btaddfromexcelActionPerformed

    private void btfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfindActionPerformed
        // TODO add your handling code here:
        DistributorObject obj = new DistributorObject();
        if(rdname.isSelected()){
            if(!txtname.getText().isEmpty()){
            obj.setDistributor_name(txtname.getText());
            ResultSet rs = d.getDistributors(cond.getDistributorByNameOrAddressOrPhone(obj));
            tbldanhsach.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên nhà phân phối để tìm");
            }
        }
        else if(rdaddress.isSelected()){
            if(!txtaddress.getText().isEmpty()){
                obj.setDistributor_address(txtaddress.getText());
                ResultSet rs = d.getDistributors(cond.getDistributorByNameOrAddressOrPhone(obj));
                tbldanhsach.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập địa chỉ nhà phân phối để tìm.");
            }
        }
        else if(rdphone.isSelected()){
            if(!txtphone.getText().isEmpty()){
                obj.setDistributor_phone(txtphone.getText());
                ResultSet rs = d.getDistributors(cond.getDistributorByNameOrAddressOrPhone(obj));
                tbldanhsach.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập số điện thoại nhà phân phối để tìm");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn thông tin cần tìm ?");
        }
    }//GEN-LAST:event_btfindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DistributorName;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btaddfromexcel;
    private javax.swing.JButton btdel;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btfind;
    private javax.swing.ButtonGroup btgroup;
    private javax.swing.JButton btreload;
    private javax.swing.JButton btreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdaddress;
    private javax.swing.JRadioButton rdname;
    private javax.swing.JRadioButton rdphone;
    private javax.swing.JTable tbldanhsach;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtimamount;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
