/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chinsu.gui1;

import chinsu.Utilities.CreateBarcode;
import chinsu.Utilities.ReadFromExcel;
import chinsu.object.equipment.Equipment;
import chinsu.object.equipment.EquipmentImpl;
import chinsu.object.equipment.EquipmentObject;
import chinsu.object.sql.Conditions;
import chinsu.object.type.TypeImpl;
import chinsu.object.type.TypeObject;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import chinsu.object.type.Type;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.util.Date;
import java.sql.NClob;
import java.sql.Ref;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Statement;
import java.sql.Time;
import java.sql.Timestamp;
import java.text.ParseException;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;

/**
 *
 * @author Windows 10
 */
public class EquipmentJpanel extends javax.swing.JPanel {

    /**
     * Creates new form EquipmentJpanel
     */
    Equipment e = new EquipmentImpl();
    TypeImpl t = new TypeImpl();
    Conditions cond = new Conditions();
    HashMap<Integer,String> map = new HashMap<Integer,String>();
    public EquipmentJpanel() {
        
        initComponents();
        try{
        ResultSet rs = t.getTypes("");
        while(rs.next()){
            map.put(rs.getInt("type_id"),rs.getString("type_name"));
//                int id = rs.getInt("type_id");
//                String name = rs.getString("type_name");
//                cbbtype.addItem(id + " - " + name);
        }
        for(String value:map.values()){
            cbbtype.addItem(value);
        }
        
    }
    catch (SQLException ex){
         Logger.getLogger(EquipmentJpanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgroup = new javax.swing.ButtonGroup();
        txtimprice = new javax.swing.JTextField();
        txtexprice = new javax.swing.JTextField();
        cbbtype = new javax.swing.JComboBox<>();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btreload = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        btdel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdname = new javax.swing.JRadioButton();
        rdid = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rdloai = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btfind = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldanhsach = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        btexcel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtphotopath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btreset = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtUrlBarcode = new javax.swing.JTextField();
        jlbBarcode = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));

        txtimprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtimprice.setMaximumSize(new java.awt.Dimension(6, 20));

        txtexprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtexprice.setMaximumSize(new java.awt.Dimension(6, 20));
        txtexprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexpriceActionPerformed(evt);
            }
        });

        cbbtype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbtype.setMaximumSize(new java.awt.Dimension(28, 20));
        cbbtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbtypeItemStateChanged(evt);
            }
        });
        cbbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbtypeActionPerformed(evt);
            }
        });

        txtdate.setMaximumSize(new java.awt.Dimension(27, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ngày xuất");

        btreload.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btreload.setText("Reload");
        btreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreloadActionPerformed(evt);
            }
        });

        btadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btadd.setText("Thêm");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        btedit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btedit.setText("Sửa");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        btdel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btdel.setText("Xóa");
        btdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã thiết bị");

        btgroup.add(rdname);
        rdname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdname.setText("Tên thiết bị");
        rdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnameActionPerformed(evt);
            }
        });

        btgroup.add(rdid);
        rdid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdid.setText("Mã thiết bị");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên thiết bị");

        btgroup.add(rdloai);
        rdloai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdloai.setText("Loại thiết bị");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số lượng");

        btfind.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btfind.setText("Tìm kiếm");
        btfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfindActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Loại thiết bị");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá nhập");

        tbldanhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thiết bị", "Tên thiết bị", "Số lượng", "Loại thiết bị", "Đơn giá nhập", "Đơn giá xuất", "Ngày xuất"
            }
        ));
        tbldanhsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldanhsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldanhsach);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Đơn giá xuất");

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.setMaximumSize(new java.awt.Dimension(6, 20));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setMaximumSize(new java.awt.Dimension(6, 20));

        txtamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtamount.setMaximumSize(new java.awt.Dimension(6, 20));

        btexcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btexcel.setText("Thêm từ excel");
        btexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ảnh:");

        txtphotopath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtphotopath.setMaximumSize(new java.awt.Dimension(6, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setText("Quản lí hàng ");

        btreset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Url barcode");

        txtUrlBarcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtBarcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtimprice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtexprice, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1025, 1025, 1025)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel10)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBarcode)
                                    .addComponent(txtphotopath, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdname)
                                    .addComponent(rdloai)
                                    .addComponent(rdid))
                                .addGap(9, 9, 9)
                                .addComponent(btfind))
                            .addComponent(btexcel)))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(25, 25, 25)
                        .addComponent(txtUrlBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btreload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btadd)
                        .addGap(156, 156, 156)
                        .addComponent(btreset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btedit)
                                .addGap(18, 18, 18)
                                .addComponent(btdel)))))
                .addGap(580, 580, 580))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtimprice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtexprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtUrlBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdname)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdid)
                                    .addComponent(btfind))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdloai))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtphotopath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlbBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btreload)
                    .addComponent(btadd)
                    .addComponent(btedit)
                    .addComponent(btdel)
                    .addComponent(btreset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreloadActionPerformed
        // TODO add your handling code here:
        ResultSet rs = e.getEquipments("");
        tbldanhsach.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btreloadActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().trim().isEmpty()||txtimprice.getText().trim().isEmpty()||txtexprice.getText().trim().isEmpty()||txtamount.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ lượng thông tin");
        }
        else{
            EquipmentObject eo = new EquipmentObject();
            eo.setEquipment_name(txtname.getText());
            eo.setEquipment_amount(Integer.parseInt(txtamount.getText()));
            for(Map.Entry<Integer,String> entry : map.entrySet()){
                if(entry.getValue() == cbbtype.getSelectedItem()){
                    eo.setEquipment_type_id(entry.getKey());
                }
            }
            eo.setEquipment_imprice(Float.parseFloat(txtimprice.getText()));
            eo.setEquipment_exprice(Float.parseFloat(txtexprice.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            eo.setEquipment_imdate(sdf.format(txtdate.getDate()));
            eo.setEquipment_image(txtphotopath.getText());
            eo.setEquipment_barcode(CreateBarcode.createBR(txtUrlBarcode.getText(), txtname.getText()));
            
            if (e.addEquipment(eo)){
                JOptionPane.showMessageDialog(null, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Loại hàng đã tồn tại");
            }
        }
        btreloadActionPerformed(evt);

    }//GEN-LAST:event_btaddActionPerformed

    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        if (txtname.getText().trim().isEmpty() || txtimprice.getText().trim().isEmpty()||txtexprice.getText().trim().isEmpty() || txtamount.getText().trim().isEmpty()||txtid.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ các trường dữ liệu");
        } else {
            EquipmentObject eo = new EquipmentObject();
            eo.setEquipment_id(Integer.parseInt(txtid.getText()));
            eo.setEquipment_name(txtname.getText());
            eo.setEquipment_amount(Integer.parseInt(txtamount.getText()));
            for(Map.Entry<Integer,String> entry: map.entrySet()){
                if(entry.getValue() == cbbtype.getSelectedItem()){
                    eo.setEquipment_type_id(entry.getKey());
                }
            }
            eo.setEquipment_imprice(Float.parseFloat(txtimprice.getText()));
            eo.setEquipment_exprice(Float.parseFloat(txtexprice.getText()));
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            eo.setEquipment_imdate(sdf.format(txtdate.getDate()));
            eo.setEquipment_image(txtphotopath.getText());
            eo.setEquipment_barcode(CreateBarcode.createBR(txtUrlBarcode.getText(), txtname.getText()));
            if (e.editEquipment(eo)) {
                JOptionPane.showMessageDialog(null, "Sửa thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Hàng không tồn tại");
            }
        }
        btreloadActionPerformed(evt);
    }//GEN-LAST:event_bteditActionPerformed

    private void btdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelActionPerformed
        // TODO add your handling code here:
        if (txtid.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nhập id hàng cần xóa");
        } else {
            EquipmentObject eo = new EquipmentObject();
            eo.setEquipment_id(Integer.parseInt(txtid.getText()));
            if (e.delEquipment(eo)) {
                JOptionPane.showMessageDialog(null, "Xóa thành công");
            } else {
                JOptionPane.showMessageDialog(null, "Lỗi!!!");
            }
        }
        btreloadActionPerformed(evt);
    }//GEN-LAST:event_btdelActionPerformed

    private void tbldanhsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldanhsachMouseClicked
        // TODO add your handling code here:
        try {
            int index = tbldanhsach.getSelectedRow();
            TableModel model = tbldanhsach.getModel();
            txtid.setText(model.getValueAt(index, 0).toString());
            txtname.setText(model.getValueAt(index, 1).toString());
            txtamount.setText(model.getValueAt(index, 2).toString());
            //type
            for(Map.Entry<Integer,String> entry : map.entrySet()){
                if(entry.getKey() == Integer.parseInt(model.getValueAt(index, 3).toString())){
                    cbbtype.setSelectedItem(entry.getValue());
                }
            }
            txtimprice.setText(model.getValueAt(index, 4).toString());
            txtexprice.setText(model.getValueAt(index,5).toString());
            //date
            Date date;
            date = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(index, 6).toString());
            txtdate.setDate(date);
            //image
            BufferedImage image = null;
            ImageIcon icon = null;
            try {
                txtphotopath.setText(model.getValueAt(index, 7).toString());
                image = ImageIO.read(new File(txtphotopath.getText()));
                icon = new ImageIcon(image.getScaledInstance(177, 122, image.SCALE_SMOOTH));
                lblimage.setIcon(icon);
                
                
                
            } catch (IOException ex) {
                Logger.getLogger(EquipmentJpanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                txtBarcode.setText(model.getValueAt(index, 8).toString());
                image = ImageIO.read(new File(txtBarcode.getText()));
                icon = new ImageIcon(image.getScaledInstance(177, 122, image.SCALE_SMOOTH));
                jlbBarcode.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(EquipmentJpanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            //barcode
            
        } catch (ParseException ex) {
            Logger.getLogger(EquipmentJpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbldanhsachMouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcelActionPerformed
        // TODO add your handling code here:
        ExcelAddEquipment ex = new ExcelAddEquipment();
        ex.setVisible(true);
    }//GEN-LAST:event_btexcelActionPerformed

    private void rdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdnameActionPerformed

    private void btfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfindActionPerformed
        // TODO add your handling code here:
        EquipmentObject eo1 = new EquipmentObject();
        if(rdname.isSelected()){
            if(!txtname.getText().isEmpty()){
            eo1.setEquipment_name(txtname.getText());
            ResultSet rs = e.getEquipments(cond.getEquipmentByNameOrByEquipmentTypeId(eo1));
            tbldanhsach.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
                JOptionPane.showMessageDialog(null,"Bạn phải nhập tên cần tìm");
            }
        }
        else if(rdloai.isSelected()){
            EquipmentObject eo2 = new EquipmentObject();
            for(Map.Entry<Integer,String> entry: map.entrySet()){
                if(entry.getValue() == cbbtype.getSelectedItem()){
                    eo2.setEquipment_type_id(entry.getKey());
                    ResultSet rs = e.getEquipments(cond.getEquipmentByNameOrByEquipmentTypeId(eo2));
                    tbldanhsach.setModel(DbUtils.resultSetToTableModel(rs));
                }
            }
        }
        else if(rdid.isSelected()){
            if(!txtid.getText().isEmpty()){
            ResultSet rs = e.getEquipment(Integer.parseInt(txtid.getText()));
            tbldanhsach.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
                JOptionPane.showMessageDialog(null,"Bạn phải nhập tên cần tìm");
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Bạn phải chọn mục cần tìm");
        }
    }//GEN-LAST:event_btfindActionPerformed

    private void cbbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbtypeActionPerformed

    private void cbbtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbtypeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbtypeItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn ảnh");
        chooser.showOpenDialog(null);
        if(JFileChooser.APPROVE_OPTION == 0){
            File selectedphoto = chooser.getSelectedFile();
            String url = selectedphoto.getAbsolutePath();
            txtphotopath.setText(url);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
        txtid.setText("");
        txtname.setText("");
        txtamount.setText("");
        txtimprice.setText("");
        txtexprice.setText("");
        txtUrlBarcode.setText("");
        txtphotopath.setText("");
        
    }//GEN-LAST:event_btresetActionPerformed

    private void txtexpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexpriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btdel;
    private javax.swing.JButton btedit;
    private javax.swing.JButton btexcel;
    private javax.swing.JButton btfind;
    private javax.swing.ButtonGroup btgroup;
    private javax.swing.JButton btreload;
    private javax.swing.JButton btreset;
    private javax.swing.JComboBox<String> cbbtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbBarcode;
    private javax.swing.JLabel lblimage;
    private javax.swing.JRadioButton rdid;
    private javax.swing.JRadioButton rdloai;
    private javax.swing.JRadioButton rdname;
    private javax.swing.JTable tbldanhsach;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtUrlBarcode;
    private javax.swing.JTextField txtamount;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtexprice;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtimprice;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphotopath;
    // End of variables declaration//GEN-END:variables
}
