/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chinsu.gui1;

import chinsu.Utilities.ReadFromExcel;
import chinsu.object.distributor.DistributorImpl;
import chinsu.object.distributor.DistributorObject;
import chinsu.object.distributor.Distributor;
import chinsu.object.user.User;
import chinsu.object.user.UserImpl;
import chinsu.object.user.UserObject;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kieun
 */
public class ExcelAddDistributor extends javax.swing.JFrame {

    /**
     * Creates new form ExcelAddDistributor
     */
    String col[] = {"Tên", "Địa chỉ","Số điện thoại","Số lượng"};

    DefaultTableModel tableModel = new DefaultTableModel(col, 0);
    JTable table = new JTable(tableModel);
    Vector<DistributorObject> dobj = null;
    Distributor dis = new DistributorImpl();
    public ExcelAddDistributor() {
        tableModel.setRowCount(0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListExcel = new javax.swing.JTable();
        btexit = new javax.swing.JButton();
        btchoosefile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btadd.setText("Thêm");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        tblListExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblListExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblListExcel);

        btexit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btexit.setText("Thoát");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        btchoosefile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btchoosefile.setText("Chọn file excel");
        btchoosefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchoosefileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btchoosefile, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btchoosefile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thêm?", "ChinSu?", JOptionPane.YES_NO_OPTION);
        int flag = 0;
        if (reply == JOptionPane.YES_OPTION) {
            for(DistributorObject distributor : dobj) {
                if(!dis.addDistributor(distributor)) {
                    flag++;
                }
            }
            dobj = null;
            JOptionPane.showMessageDialog(null, "Có " + flag + "bản ghi bị lỗi");
        } else {
            JOptionPane.showMessageDialog(null, "GOODBYE");
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_btexitActionPerformed

    private void btchoosefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchoosefileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn excel");
        chooser.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == 0) {
           try {
                File selectedFile = chooser.getSelectedFile();
                String url = selectedFile.getPath();
                dobj = ReadFromExcel.readDistributorFromExcel(url);
                for (DistributorObject d : dobj) {
                    Vector record = new Vector();
                    record.add(d.getDistributor_name());
                    record.add(d.getDistributor_address());
                    record.add(d.getDistributor_phone());
                    record.add(d.getDistributor_imamount());
                    tableModel.addRow(record);
                }
                tblListExcel.setModel(tableModel);
            } catch (IOException ex) {
                Logger.getLogger(ExcelAddDistributor.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btchoosefileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcelAddDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcelAddDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcelAddDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcelAddDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcelAddDistributor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btchoosefile;
    private javax.swing.JButton btexit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListExcel;
    // End of variables declaration//GEN-END:variables
}
