/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chinsu.gui1;

import chinsu.Utilities.CreateBarcode;
import chinsu.Utilities.ReadFromExcel;
import chinsu.object.distributor.DistributorObject;
import chinsu.object.equipment.EquipmentImpl;
import chinsu.object.equipment.Equipment;
import chinsu.object.equipment.EquipmentObject;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kieun
 */
public class ExcelAddEquipment extends javax.swing.JFrame {

    /**
     * Creates new form ExcelAddEquipment
     */
     String col[] = {"Tên", "Số lượng","Mã loại","đơn giá nhập","đơn giá xuất","ngày nhập","url ảnh","barcode"};
    DefaultTableModel tableModel = new DefaultTableModel(col, 0);
    JTable table = new JTable(tableModel);
    Vector<EquipmentObject> eobj = null;
    Equipment equ = new EquipmentImpl();
    public ExcelAddEquipment() {
        tableModel.setRowCount(0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListExcel = new javax.swing.JTable();
        btexit = new javax.swing.JButton();
        btfromexcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btadd.setText("Thêm");
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });

        tblListExcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblListExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(tblListExcel);

        btexit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btexit.setText("Thoát");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        btfromexcel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btfromexcel.setText("Chọn file excel");
        btfromexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfromexcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btfromexcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btadd, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btexit)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btfromexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thêm?", "anhhungchinsu", JOptionPane.YES_NO_OPTION);
        int flag = 0;
        if (reply == JOptionPane.YES_OPTION) {
            for(EquipmentObject equipment : eobj) {
                equipment.setEquipment_barcode(CreateBarcode.createBR(equipment.getEquipment_barcode(), equipment.getEquipment_name()));
                if(!equ.addEquipment(equipment)){
                    flag++;
                }
            }
            eobj = null;
            JOptionPane.showMessageDialog(null, "Có " + flag + "bản ghi bị lỗi");
        } else {
            JOptionPane.showMessageDialog(null, "GOODBYE");
        }
    }//GEN-LAST:event_btaddActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_btexitActionPerformed

    private void btfromexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfromexcelActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn excel");
        chooser.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == 0) {
         try {
                File selectedFile = chooser.getSelectedFile();
                String url = selectedFile.getPath();
                eobj = ReadFromExcel.readEquipmentFromExcel(url);
                for (EquipmentObject u : eobj) {
                    Vector record = new Vector();
                    record.add(u.getEquipment_name());
                    record.add(u.getEquipment_amount());
                    record.add(u.getEquipment_type_id());
                    record.add(u.getEquipment_imprice());
                    record.add(u.getEquipment_exprice());
                    record.add(u.getEquipment_imdate());
                    record.add(u.getEquipment_image());
                    record.add(u.getEquipment_barcode());
                    tableModel.addRow(record);
                }
                tblListExcel.setModel(tableModel);
        } catch (IOException ex) {
                Logger.getLogger(ExcelAddEquipment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btfromexcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcelAddEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcelAddEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcelAddEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcelAddEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcelAddEquipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btadd;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btfromexcel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListExcel;
    // End of variables declaration//GEN-END:variables
}
