/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chinsu.gui1;

import chinsu.Utilities.WriteExportToExcel;
import chinsu.object.equipment.Equipment;
import chinsu.object.equipment.EquipmentImpl;
import chinsu.object.equipment.EquipmentObject;
import chinsu.object.export.Export;
import chinsu.object.export.ExportImpl;
import chinsu.object.export.ExportObject;
import chinsu.object.export_detail.ExportDetail;
import chinsu.object.export_detail.ExportDetailImpl;
import chinsu.object.export_detail.ExportDetailObject;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author kieun
 */
public class ExportJpanel extends javax.swing.JPanel {

    Equipment e = new EquipmentImpl();
    Export exp = new ExportImpl();
    ExportDetail expd = new ExportDetailImpl();
    DefaultListModel listModel = new DefaultListModel();
    DefaultListModel listModel1 = new DefaultListModel();
    float totalPrice = 0;

    /**
     * Creates new form BillDetailJPanel
     */
    public ExportJpanel() {
        initComponents();
        txtNhanVien.setText(MainFrame.userName);
        txtDateSystem.setText(java.time.LocalDate.now().toString());
        this.takeDataToJList();
        listEquipment.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    try {
                        JList source = (JList) event.getSource();
                        String selected = source.getSelectedValue().toString();
                        txtNameEquipment.setText(selected);
                        ResultSet rs = e.getEquipments("equipment_name='" + selected + "'");
                        while (rs.next()) {
                            txtIdEquipment.setText(Integer.toString(rs.getInt("equipment_id")));
                            txtEquipmentDate.setText(rs.getString("equipment_imdate"));
                            txtEquipmentPrice.setText(Float.toString(rs.getFloat("equipment_exprice")));
                            txtEquipmentAmount.setText(Integer.toString(rs.getInt("equipment_amount")));
                            ImageIcon icon = new ImageIcon(rs.getString("equipment_image"));
                            jlbImage.setIcon(icon);
                            ImageIcon barcode = new ImageIcon(rs.getString("equipment_barcode"));
                            jlbBarcode.setIcon(barcode);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(ExportJpanel.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        });
    }

    private ArrayList getListEquipments() {
        ArrayList names = new ArrayList();
        ResultSet rs = e.getEquipments("");
        try {
            while (rs.next()) {
                names.add(rs.getString("equipment_name"));
            }
            return names;
        } catch (SQLException ex) {
            Logger.getLogger(ExportJpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private void takeDataToJList() {
        for (Object name : getListEquipments()) {
            listModel.addElement(name);
        }
        listEquipment.setModel(listModel);
        listEquipment.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void filterSearch(String searchString) {
        DefaultListModel filterItem = new DefaultListModel();
        ArrayList list = getListEquipments();
        for (Object item : list) {
            String name = item.toString().toLowerCase();
            if (name.contains(searchString.toLowerCase())) {
                filterItem.addElement(item);
            }
        }
        listModel = filterItem;
        listEquipment.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listEquipment = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNameCustomer = new javax.swing.JTextField();
        txtAgeCustomer = new javax.swing.JTextField();
        txtAdressCustomer = new javax.swing.JTextField();
        txtPhoneCustomer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdEquipment = new javax.swing.JTextField();
        txtNameEquipment = new javax.swing.JTextField();
        txtTotalEquipment = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listExport = new javax.swing.JList<>();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCancelAll = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEquipmentPrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEquipmentDate = new javax.swing.JTextField();
        txtEquipmentAmount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jlbImage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JTextField();
        txtDateSystem = new javax.swing.JTextField();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jlbBarcode = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jScrollPane1.setViewportView(listEquipment);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên khách hàng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tuổi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Địa chỉ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại");

        txtNameCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtAgeCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtAdressCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPhoneCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Mã sản phẩm");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tên sản phẩm");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số lượng");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("THÀNH TIỀN");

        txtIdEquipment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdEquipment.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIdEquipment.setEnabled(false);

        txtNameEquipment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNameEquipment.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNameEquipment.setEnabled(false);

        txtTotalEquipment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jScrollPane2.setViewportView(listExport);

        btnConfirm.setText("Thêm vào giỏ");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Hủy mặt hàng");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCancelAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelAll.setText("Hủy toàn bộ");
        btnCancelAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAllActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Giá");

        txtEquipmentPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEquipmentPrice.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEquipmentPrice.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Ngày nhập");

        txtEquipmentDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEquipmentDate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEquipmentDate.setEnabled(false);

        txtEquipmentAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEquipmentAmount.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEquipmentAmount.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Số lượng mua");

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xuất hóa đơn");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nhân viên");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Ngày");

        txtNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNhanVien.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNhanVien.setEnabled(false);

        txtDateSystem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDateSystem.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDateSystem.setEnabled(false);
        txtDateSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateSystemActionPerformed(evt);
            }
        });

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Tổng tiền");

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbltitle.setText("Xuất hóa đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNameCustomer)
                                    .addComponent(txtAgeCustomer)
                                    .addComponent(txtAdressCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDateSystem, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPhoneCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(216, 216, 216)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel10)
                                                                .addComponent(jLabel8))
                                                            .addGap(65, 65, 65)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel6)
                                                            .addComponent(jLabel11))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtEquipmentAmount)
                                                            .addComponent(txtEquipmentDate)
                                                            .addComponent(txtEquipmentPrice)
                                                            .addComponent(txtNameEquipment)
                                                            .addComponent(txtIdEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnCancelAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTotalEquipment)
                                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(302, 302, 302)
                                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(213, 213, 213)))
                .addComponent(jlbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jlbBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltitle)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(txtDateSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(txtPhoneCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNameEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtEquipmentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(txtEquipmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(txtEquipmentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCancel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancelAll)))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtTotalEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirm))
                            .addComponent(jlbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNameCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAgeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAdressCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        filterSearch(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        if (txtTotalEquipment.getText().isEmpty() || Integer.parseInt(txtAmount.getText()) == 0.0 || Float.parseFloat(txtTotalEquipment.getText()) == 0) {
            JOptionPane.showMessageDialog(null, "Nhập số lượng");
        } else {
            String temp = txtIdEquipment.getText() + "  -  " + txtNameEquipment.getText() + "  -  " + txtEquipmentPrice.getText() + "  -  " + txtAmount.getText() + "  -  " + txtTotalEquipment.getText();
            listModel1.addElement(temp);
            listExport.setModel(listModel1);
            totalPrice += Float.parseFloat(txtTotalEquipment.getText());
            txtTotalPrice.setText(Float.toString(totalPrice));
        }

    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int index = listExport.getSelectedIndex();
        String[] temp = listExport.getSelectedValue().split("  -  ");
        totalPrice -= Float.parseFloat(temp[4]);
        txtTotalPrice.setText(Float.toString(totalPrice));
        listModel1.removeElementAt(index);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAllActionPerformed
        // TODO add your handling code here:
        totalPrice = 0;
        txtTotalPrice.setText(Float.toString(totalPrice));
        listModel1.clear();
        listExport.setModel(listModel1);
    }//GEN-LAST:event_btnCancelAllActionPerformed

    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
        // TODO add your handling code here:
        if (Integer.parseInt(txtAmount.getText()) > Integer.parseInt(txtEquipmentAmount.getText())) {
            JOptionPane.showMessageDialog(null, "Không vượt quá số lượng hiện có");
            txtTotalEquipment.setText("0.0");
        } else {
            Float p = Float.parseFloat(txtEquipmentPrice.getText());
            Float a = Float.parseFloat(txtAmount.getText());
            String total = Float.toString(p * a);
            txtTotalEquipment.setText(total);
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                btnConfirm.doClick();
            }
        }
    }//GEN-LAST:event_txtAmountKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<String> arr = new ArrayList();
        for (int i = 0; i < listModel1.getSize(); i++) {
            String o = (String) listModel1.getElementAt(i);
            arr.add(o);
        }
        int reply = JOptionPane.showConfirmDialog(null, "BẠN CÓ CHẮC CHẮN MUỐN XUẤT HÓA ĐƠN?", "CHINSU", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            WriteExportToExcel.write(txtDateSystem.getText(), txtNhanVien.getText(), txtNameCustomer.getText(), txtPhoneCustomer.getText(), Float.parseFloat(txtTotalPrice.getText()), arr);

            ExportObject expo = new ExportObject();

            String id = "";
            Calendar c = Calendar.getInstance();
            String year = Integer.toString(c.get(Calendar.YEAR));
            String month = Integer.toString(c.get(Calendar.MONTH));
            String day = Integer.toString(c.get(Calendar.DAY_OF_MONTH));
            String hour = Integer.toString(c.get(Calendar.HOUR_OF_DAY));
            String minute = Integer.toString(c.get(Calendar.MINUTE));
            String second = Integer.toString(c.get(Calendar.SECOND));
            id = day + month + year + hour + minute + second;

            expo.setExport_id(id);
            expo.setExport_user_id(MainFrame.userId);
            expo.setExport_total(Float.parseFloat(txtTotalPrice.getText()));
            expo.setExport_customer_name(txtNameCustomer.getText());
            expo.setExport_customer_phone(txtPhoneCustomer.getText());
            expo.setExport_date(txtDateSystem.getText());
            exp.addExport(expo);

            for (int i = 0; i < arr.size(); i++) {
                ExportDetailObject expdo = new ExportDetailObject();
                expdo.setExport_detail_export_id(id);
                String[] temp = arr.get(i).split("  -  ");
                for(int j = 0; j<6; j++) {
                    expdo.setExport_detail_amount(Integer.parseInt(temp[3]));
                    expdo.setExport_detail_equipment_id(Integer.parseInt(temp[0]));
                    expdo.setExport_detail_total(Float.parseFloat(temp[4]));
                }
                expd.addExportDetail(expdo);
            }
            
            for(int i = 0; i<listModel1.getSize(); i++) {
                Object o = listModel1.getElementAt(i);
                String[] item = o.toString().split("  -  ");
                e.updateAmount(Integer.parseInt(item[0]), Integer.parseInt(item[3]));
            }
            
            listModel1.clear();
            listExport.setModel(listModel1);
        } else {
            JOptionPane.showMessageDialog(null, "CẢM ƠN ĐÃ BẢO VỆ MÔI TRƯỜNG :/");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDateSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateSystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateSystemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelAll;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlbBarcode;
    private javax.swing.JLabel jlbImage;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JList<String> listEquipment;
    private javax.swing.JList<String> listExport;
    private javax.swing.JTextField txtAdressCustomer;
    private javax.swing.JTextField txtAgeCustomer;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDateSystem;
    private javax.swing.JTextField txtEquipmentAmount;
    private javax.swing.JTextField txtEquipmentDate;
    private javax.swing.JTextField txtEquipmentPrice;
    private javax.swing.JTextField txtIdEquipment;
    private javax.swing.JTextField txtNameCustomer;
    private javax.swing.JTextField txtNameEquipment;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtPhoneCustomer;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotalEquipment;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
